const initialTestData = {
    completeBloodCount: {},
    automatedDifferential: {},
    generalChemistry: {},
    hepaticFunctionPanel: {},
    lipidPanel: {},
    ironAndTIBC: {},
    thyroidTesting: {},
    tumorMarkers: {},
    endocrineEvaluation: {},
    medicalLab: '',
    physician: '',
    fasting: '',
    accountNumber: '',
    chartNumber: '',
    firstReportedOn: '',
    collectionDate: '',
    collectionTime: '',
    receivalDate: '',
    receivalTime: '',
    finalReportDate: '',
    printDate: '',
    printTime: '',
    reportId: '',
    reportStatus: '',
    testDate: '',
};

export default initialTestData;